[package]
name = "tud-presentation"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Jakob Listabarth <https://github.com/jakoblistabarth>"]
license = "MIT"
description = "Presentation template for TU Dresden (Technische Universität Dresden)."
repository = "https://github.com/jakoblistabarth/tud-presentation-typst"
keywords = ["TUD", "Technische Universität Dresden", "Presentation"]
categories = ["presentation"]
exclude = ["template/main.pdf"]

[template]
path = "template/"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"